### ISSUE TITLE
A playing command that returns information about the current playing track

### ISSUE THREAD

**Issue by BeeLazy** [BeeLazy/DJ-Helper#13]

**Comment by basnetaakash23** [comment]
@BeeLazy Can you give me requirements.txt for this project so i can work on it.

**Comment by BeeLazy** [comment]
Hi @basnetaakash23 
I've updated the project with the pip requirements in #15. 

In addition to that, you need to have a Lavalink server. They have a docker image, or you can run the Lavalink.jar in java with:
```code
java -jar Lavalink.jar
```
They recommend Oracle Java 13. I've tested it on Ubuntu 22.04 with openjdk 18, and that has worked just fine for me. 

After having the Lavalink server sorted, you start bot by running bot.py in python:
```code
python3 bot.py
```

On Ubuntu this would total to something like:
```code
mkdir ~/dj-player
cd ~/dj-player
git clone https://github.com/BeeLazy/DJ-Helper.git .
sudo apt-get install openjdk-18-jre-headless
sudo apt-get install pip
pip3 install -U wavelink
pip3 install -U discord.py
pip3 install -U python-dotenv
pip3 install -U youtube_dl
```
Some of the settings are stored in environment variables. On Ubuntu one could f.ex store those in a .env file or in the global environment file:
```code
nano ~/dj-helper/.env
sudo nano /etc/environment
source /etc/environment
echo $LAVALINK_PORT
```
Now that we have that sorted, we should be ready to run the bot:
```code
java -jar Lavalink.jar
python3 bot.py
```
Not tested this yet, but should be something close it at least :)
I plan on writing more install instructions, that I have also tested, in #7

**Comment by BeeLazy** [comment]
@basnetaakash23 , a bit later in development, we will probably also have:
 - [Dropbox](https://dropbox-sdk-python.readthedocs.io) to help solve filestorage needs like the one in #2 
 - [MongoDD](https://github.com/mongodb/mongo) for persistent storage of usersettings, playlists etc

We'll see what we need when we get that far in development
