### ISSUE TITLE
See what is currently playing

### ISSUE THREAD

**Issue by BeeLazy** [BeeLazy/DJ-Helper#5]
When the bot starts playing a new song, it should update the embedded channel player (the message sent to the channel) with song information. Probably best done by implementing [wavelink.on_wavelink_track_start](https://wavelink.readthedocs.io/en/latest/wavelink.html#wavelink.on_wavelink_track_start)(player: [Player](https://wavelink.readthedocs.io/en/latest/wavelink.html#wavelink.Player), track: [Track](https://wavelink.readthedocs.io/en/latest/wavelink.html#wavelink.Track))

**Comment by basnetaakash23** [comment]
@BeeLazy I can help you out here. Can you describe more on what you are looking for here?

**Comment by BeeLazy** [comment]
Hello @basnetaakash23, and thank you for showing interest in the project. 

I've updated the description with a little bit more information. That said. It is still very early in this project, so it does not have much structure and code yet.
